services:
  postgres-app:
    build: .
    env_file:
      - .env
    ports:
      - '8090:8090'
    networks:
      - backend-network
    volumes:
      - .:/app
      - /app/node_modules

  backend:
    build: .
    env_file:
      - .env
    ports:
      - 8090:8090
    depends_on:
      - database-mariadb
    volumes:
      - .:/app
      - /app/node_modules

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  database-mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: petclinic
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db-files/MariaDB:/docker-entrypoint-initdb.d
  
  database-postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: petclinic
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db-files/Postgres:/docker-entrypoint-initdb.d
      
networks:
  backend-network:
    external: true
  prisma-network:

volumes:
  mariadb_data:
  pgdata: